import type { FleetData } from "./types";

// Données importées depuis le classeur Excel de la flotte.
// Régénérable via: python3 scripts/seed_from_xlsx.py <fichier.xlsx>
export const seedData: FleetData = {
  vehicles: [
    {"id": "v1", "plate": "GC-885-LB", "brand": "Porsche", "model": "", "year": 2021, "fuel": "essence", "status": "active", "mileage": 43018, "nextServiceKm": 50000, "assignedDriverId": "d1"},
    {"id": "v2", "plate": "GT-565-XR", "brand": "MG", "model": "Marvel R", "year": 2025, "fuel": "electrique", "status": "active", "mileage": 27737, "nextServiceKm": 30000, "assignedDriverId": "d2"},
    {"id": "v3", "plate": "GD-056-CR", "brand": "Mercedes", "model": "", "year": 2021, "fuel": "essence", "status": "active", "mileage": 76851, "nextServiceKm": 80000, "assignedDriverId": "d3"},
    {"id": "v4", "plate": "GE-349-FZ", "brand": "Mercedes", "model": "", "year": 2022, "fuel": "essence", "status": "active", "mileage": 74207, "nextServiceKm": 80000, "assignedDriverId": "d4"},
    {"id": "v5", "plate": "HG-763-VP", "brand": "BYD", "model": "Atto 3", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d4"},
    {"id": "v6", "plate": "GR-745-LR", "brand": "Dacia", "model": "", "year": 2023, "fuel": "essence", "status": "active", "mileage": 56051, "nextServiceKm": 60000, "assignedDriverId": "d5"},
    {"id": "v7", "plate": "FF-304-GL", "brand": "Mercedes", "model": "S", "year": 2022, "fuel": "essence", "status": "active", "mileage": 186925, "nextServiceKm": 190000, "assignedDriverId": "d6"},
    {"id": "v8", "plate": "FF-777-XK", "brand": "Volvo", "model": "XC60", "year": 2019, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d7"},
    {"id": "v9", "plate": "HE-739-WP", "brand": "Toyota", "model": "CHR", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d8"},
    {"id": "v10", "plate": "GP-795-YL", "brand": "Peugeot", "model": "5008", "year": 2023, "fuel": "essence", "status": "active", "mileage": 135913, "nextServiceKm": 140000, "assignedDriverId": "d9"},
    {"id": "v11", "plate": "GW-075-EZ", "brand": "Peugeot", "model": "5008", "year": 2023, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d10"},
    {"id": "v12", "plate": "GW-087-EZ", "brand": "Peugeot", "model": "5008", "year": 2023, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d11"},
    {"id": "v13", "plate": "GW-173-JV", "brand": "Peugeot", "model": "5008", "year": 2023, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d12"},
    {"id": "v14", "plate": "FJ-607-QH", "brand": "Peugeot", "model": "3008", "year": 2019, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d13"},
    {"id": "v15", "plate": "GP-232-WF", "brand": "Peugeot", "model": "5008", "year": 2023, "fuel": "essence", "status": "active", "mileage": 47000, "nextServiceKm": 50000, "assignedDriverId": "d14"},
    {"id": "v16", "plate": "HJ-285-FL", "brand": "BMW", "model": "X1", "year": 2026, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d15"},
    {"id": "v17", "plate": "HJ-181-RN", "brand": "Nissan", "model": "X-trail", "year": 2026, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d16"},
    {"id": "v18", "plate": "HG-709-CH", "brand": "BYD", "model": "Seal U DM-I", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d17"},
    {"id": "v19", "plate": "HF-749-VD", "brand": "Toyota", "model": "Yaris Cross", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d18"},
    {"id": "v20", "plate": "HH-613-KE", "brand": "BYD", "model": "Seal U DM-I", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d19"},
    {"id": "v21", "plate": "FZ-301-YZ", "brand": "Peugeot", "model": "5008", "year": 2021, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d20"},
    {"id": "v22", "plate": "GY-860-FG", "brand": "Audi", "model": "", "year": 2021, "fuel": "essence", "status": "active", "mileage": 96973, "nextServiceKm": 100000, "assignedDriverId": "d21"},
    {"id": "v23", "plate": "GM-548-QA", "brand": "Peugeot", "model": "3008", "year": 2022, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d22"},
    {"id": "v24", "plate": "GP-333-QJ", "brand": "Peugeot", "model": "5008", "year": 2020, "fuel": "essence", "status": "active", "mileage": 98751, "nextServiceKm": 100000, "assignedDriverId": "d23"},
    {"id": "v25", "plate": "HH-464-LQ", "brand": "BYD", "model": "Seal U DM-I", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d24"},
    {"id": "v26", "plate": "GT-818-LC", "brand": "MG4", "model": "", "year": 2023, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d25"},
    {"id": "v27", "plate": "HB-844-DE", "brand": "BYD", "model": "Seal U DM-I", "year": 2021, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d26"},
    {"id": "v28", "plate": "HB-733-DE", "brand": "BYD", "model": "Seal U DM-I", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d27"},
    {"id": "v29", "plate": "GA-313-PK", "brand": "IVECO", "model": "( Automatique )", "year": 2021, "fuel": "essence", "status": "active", "mileage": 105399, "nextServiceKm": 110000, "assignedDriverId": "d28"},
    {"id": "v30", "plate": "FR-141-MP", "brand": "Opel", "model": "VIVARO", "year": 2019, "fuel": "essence", "status": "active", "mileage": 98608, "nextServiceKm": 100000, "assignedDriverId": "d28"},
    {"id": "v31", "plate": "GA-333-PZ", "brand": "Renault", "model": "Hybrid", "year": 2021, "fuel": "hybride", "status": "active", "mileage": 82057, "nextServiceKm": 90000, "assignedDriverId": "d29"},
    {"id": "v32", "plate": "FS-224-PB", "brand": "Nissan", "model": "QASHQAI", "year": 2019, "fuel": "essence", "status": "active", "mileage": 145104, "nextServiceKm": 150000, "assignedDriverId": "d30"},
    {"id": "v33", "plate": "FZ-501-YZ", "brand": "Renault", "model": "KADJAR", "year": 2021, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d31"},
    {"id": "v34", "plate": "HH-458-LQ", "brand": "BYD", "model": "Seal U DM-I", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d32"},
    {"id": "v35", "plate": "GR-585-HP", "brand": "Dacia", "model": "Duster", "year": 2022, "fuel": "essence", "status": "active", "mileage": 68242, "nextServiceKm": 70000, "assignedDriverId": "d33"},
    {"id": "v36", "plate": "GR-302-HP", "brand": "Dacia", "model": "Duster", "year": 2022, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d34"},
    {"id": "v37", "plate": "HF-477-XW", "brand": "Hyundai", "model": "TUCSON", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d35"},
    {"id": "v38", "plate": "HJ-804-VM", "brand": "Renault", "model": "Traffic", "year": 2026, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d36"},
    {"id": "v39", "plate": "GH-994-AR", "brand": "Renault", "model": "KADJAR", "year": 2021, "fuel": "essence", "status": "active", "mileage": 131715, "nextServiceKm": 140000, "assignedDriverId": "d37"},
    {"id": "v40", "plate": "ET-095-LV", "brand": "Citroen", "model": "JUMPY", "year": 2018, "fuel": "essence", "status": "active", "mileage": 132131, "nextServiceKm": 140000, "assignedDriverId": "d38"},
    {"id": "v41", "plate": "GZ-103-JN", "brand": "DUCATI", "model": "", "year": 2024, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d39"},
    {"id": "v42", "plate": "ED-160-TZ", "brand": "Renault", "model": "Trafic", "year": 2016, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d39"},
    {"id": "v43", "plate": "FT-338-AJ", "brand": "Peugeot", "model": "3008", "year": 2020, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d40"},
    {"id": "v44", "plate": "GE-948-WY", "brand": "Renault", "model": "KADJAR", "year": 2021, "fuel": "essence", "status": "active", "mileage": 77000, "nextServiceKm": 80000, "assignedDriverId": "d41"},
    {"id": "v45", "plate": "GR-019-ZG", "brand": "Dacia", "model": "Duster", "year": 2022, "fuel": "essence", "status": "active", "mileage": 61828, "nextServiceKm": 70000, "assignedDriverId": "d30"},
    {"id": "v46", "plate": "GR-467-HP", "brand": "Dacia", "model": "Duster", "year": 2022, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d42"},
    {"id": "v47", "plate": "GQ-470-ZN", "brand": "Dacia", "model": "Duster", "year": 2022, "fuel": "essence", "status": "active", "mileage": 55673, "nextServiceKm": 60000, "assignedDriverId": "d43"},
    {"id": "v48", "plate": "6677880", "brand": "Toyota", "model": "- FENWICK", "year": 2016, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d44"},
    {"id": "v49", "plate": "GY-719-JY", "brand": "MG", "model": "ZS", "year": 2025, "fuel": "essence", "status": "active", "mileage": 25039, "nextServiceKm": 30000, "assignedDriverId": "d45"},
    {"id": "v50", "plate": "GY-720-JY", "brand": "MG", "model": "ZS", "year": 2025, "fuel": "essence", "status": "active", "mileage": 68880, "nextServiceKm": 70000, "assignedDriverId": "d46"},
    {"id": "v51", "plate": "D XP 300", "brand": "MG", "model": "ZS", "year": 2021, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d47"},
    {"id": "v52", "plate": "GY-719-JY", "brand": "MG", "model": "ZS", "year": 2025, "fuel": "essence", "status": "active", "mileage": 0, "nextServiceKm": 10000, "assignedDriverId": "d48"},
  ],
  drivers: [
    {"id": "d1", "firstName": "Jimmy", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d2", "firstName": "Lucie", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d3", "firstName": "Monsieur D", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d4", "firstName": "Maxime", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d5", "firstName": "Conu", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d6", "firstName": "Diana", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d7", "firstName": "Raphaël", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d8", "firstName": "Pauline", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d9", "firstName": "Thomas", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d10", "firstName": "Guerric", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d11", "firstName": "Charles", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d12", "firstName": "Romuald", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d13", "firstName": "FX ( A vendre )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d14", "firstName": "David ( A vendre ) faire carte grise", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d15", "firstName": "Xavi", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d16", "firstName": "Daniel", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d17", "firstName": "Nawelle", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d18", "firstName": "Martin", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d19", "firstName": "Nicolas", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d20", "firstName": "Farah", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d21", "firstName": "Frédéric", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d22", "firstName": "Enguerrand", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d23", "firstName": "Mickaël", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d24", "firstName": "Jocelyn", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d25", "firstName": "Johanna", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d26", "firstName": "Sofiane ( Remboursement )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d27", "firstName": "Shakil ( Remboursement )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d28", "firstName": "Siège", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d29", "firstName": "Ilhem ( A vendre )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d30", "firstName": "X ( A vendre )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d31", "firstName": "Halim ( A vendre )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d32", "firstName": "Sergio", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d33", "firstName": "Samira ( A vendre )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d34", "firstName": "Ahmed ( A vendre )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d35", "firstName": "Eugénie", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d36", "firstName": "Navette", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d37", "firstName": "Shaohui", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d38", "firstName": "Dépôt", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d39", "firstName": "Jérémie", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d40", "firstName": "Akram", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d41", "firstName": "Ambre ( A vendre )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d42", "firstName": "Mégane ( A vendre )", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d43", "firstName": "VENDU", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d44", "firstName": "Fenwick", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d45", "firstName": "Gionata", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d46", "firstName": "Andrea", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d47", "firstName": "Anna CORTS", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d48", "firstName": "Bram", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d49", "firstName": "Shakil", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d50", "firstName": "Mona", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d51", "firstName": "Youssouf", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d52", "firstName": "Sofiane", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d53", "firstName": "Léo", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d54", "firstName": "Ahmed", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d55", "firstName": "Yannis", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d56", "firstName": "Mr Beun", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d57", "firstName": "BYD", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d58", "firstName": "Nacim - Enguerrand", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
    {"id": "d59", "firstName": "Mégane", "lastName": "", "email": "", "phone": "", "licenseNumber": ""},
  ],
  fines: [
    {"id": "f58", "vehicleId": "", "driverId": "d54", "date": "2026-05-19", "reason": "Stationnement", "amount": 25, "location": "", "status": "pending"},
    {"id": "f59", "vehicleId": "", "driverId": "d59", "date": "2026-05-19", "reason": "Stationnement", "amount": 50, "location": "", "status": "pending"},
    {"id": "f57", "vehicleId": "", "driverId": "d58", "date": "2026-05-13", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f55", "vehicleId": "v1", "driverId": "d1", "date": "2026-04-29", "reason": "voie de Bus", "amount": 90, "location": "", "status": "paid"},
    {"id": "f56", "vehicleId": "", "driverId": "d56", "date": "2026-04-28", "reason": "Excès de vitesse", "amount": 45, "location": "", "status": "paid"},
    {"id": "f54", "vehicleId": "v11", "driverId": "d10", "date": "2026-04-23", "reason": "Stationnement", "amount": 25, "location": "", "status": "paid"},
    {"id": "f50", "vehicleId": "", "driverId": "d57", "date": "2026-04-22", "reason": "Stationnement", "amount": 150, "location": "", "status": "paid"},
    {"id": "f51", "vehicleId": "", "driverId": "d57", "date": "2026-04-22", "reason": "Stationnement", "amount": 150, "location": "", "status": "paid"},
    {"id": "f49", "vehicleId": "", "driverId": "d57", "date": "2026-04-21", "reason": "Stationnement", "amount": 150, "location": "", "status": "paid"},
    {"id": "f47", "vehicleId": "v43", "driverId": "d40", "date": "2026-04-20", "reason": "Stationnement", "amount": 17, "location": "", "status": "paid"},
    {"id": "f48", "vehicleId": "", "driverId": "d57", "date": "2026-04-20", "reason": "Stationnement", "amount": 150, "location": "", "status": "paid"},
    {"id": "f52", "vehicleId": "v4", "driverId": "d4", "date": "2026-04-20", "reason": "Stationnement", "amount": 225, "location": "", "status": "paid"},
    {"id": "f46", "vehicleId": "v1", "driverId": "d1", "date": "2026-04-14", "reason": "voie de Bus", "amount": 90, "location": "", "status": "paid"},
    {"id": "f53", "vehicleId": "v17", "driverId": "d16", "date": "2026-04-14", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f45", "vehicleId": "", "driverId": "d56", "date": "2026-04-10", "reason": "Excès de vitesse", "amount": 45, "location": "", "status": "paid"},
    {"id": "f44", "vehicleId": "v4", "driverId": "d4", "date": "2026-04-03", "reason": "Stationnement", "amount": 65, "location": "", "status": "paid"},
    {"id": "f41", "vehicleId": "v21", "driverId": "d20", "date": "2026-04-01", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f42", "vehicleId": "v21", "driverId": "d20", "date": "2026-04-01", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f43", "vehicleId": "v21", "driverId": "d20", "date": "2026-04-01", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f40", "vehicleId": "v23", "driverId": "d22", "date": "2026-03-31", "reason": "Stationnement", "amount": 50, "location": "", "status": "paid"},
    {"id": "f60", "vehicleId": "", "driverId": "d54", "date": "2026-03-25", "reason": "Inobservation", "amount": 90, "location": "", "status": "pending"},
    {"id": "f38", "vehicleId": "", "driverId": "d54", "date": "2026-03-24", "reason": "Excès de vitesse", "amount": 90, "location": "", "status": "paid"},
    {"id": "f34", "vehicleId": "v11", "driverId": "d10", "date": "2026-03-17", "reason": "Stationnement", "amount": 17, "location": "", "status": "paid"},
    {"id": "f36", "vehicleId": "v12", "driverId": "d11", "date": "2026-03-17", "reason": "Stationnement", "amount": 17, "location": "", "status": "paid"},
    {"id": "f35", "vehicleId": "v2", "driverId": "d2", "date": "2026-03-14", "reason": "voie de Bus", "amount": 90, "location": "", "status": "paid"},
    {"id": "f37", "vehicleId": "v9", "driverId": "d8", "date": "2026-03-11", "reason": "Excès de vitesse Belgique", "amount": 64, "location": "", "status": "paid"},
    {"id": "f33", "vehicleId": "v12", "driverId": "d11", "date": "2026-03-10", "reason": "Excès de vitesse", "amount": 45, "location": "", "status": "paid"},
    {"id": "f39", "vehicleId": "v52", "driverId": "d48", "date": "2026-03-10", "reason": "Excès de vitesse", "amount": 53, "location": "", "status": "paid"},
    {"id": "f28", "vehicleId": "v43", "driverId": "d40", "date": "2026-03-05", "reason": "Excès de vitesse", "amount": 45, "location": "", "status": "paid"},
    {"id": "f30", "vehicleId": "", "driverId": "d53", "date": "2026-03-03", "reason": "Stationnement", "amount": 75, "location": "", "status": "paid"},
    {"id": "f31", "vehicleId": "", "driverId": "d55", "date": "2026-03-03", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f29", "vehicleId": "", "driverId": "d53", "date": "2026-03-02", "reason": "Stationnement", "amount": 50, "location": "", "status": "paid"},
    {"id": "f32", "vehicleId": "v11", "driverId": "d10", "date": "2026-02-26", "reason": "Stationnement", "amount": 25, "location": "", "status": "paid"},
    {"id": "f27", "vehicleId": "", "driverId": "d54", "date": "2026-02-25", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f25", "vehicleId": "v1", "driverId": "d1", "date": "2026-02-21", "reason": "Voie de Bus", "amount": 90, "location": "", "status": "paid"},
    {"id": "f21", "vehicleId": "", "driverId": "d53", "date": "2026-02-18", "reason": "Stationnement", "amount": 50, "location": "", "status": "paid"},
    {"id": "f22", "vehicleId": "", "driverId": "d53", "date": "2026-02-18", "reason": "Stationnement", "amount": 52, "location": "", "status": "paid"},
    {"id": "f24", "vehicleId": "v21", "driverId": "d20", "date": "2026-02-17", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f17", "vehicleId": "v23", "driverId": "d22", "date": "2026-02-11", "reason": "Stationnement", "amount": 50, "location": "", "status": "paid"},
    {"id": "f23", "vehicleId": "v26", "driverId": "d25", "date": "2026-02-11", "reason": "Excès de vitesse", "amount": 45, "location": "", "status": "paid"},
    {"id": "f18", "vehicleId": "", "driverId": "d52", "date": "2026-02-10", "reason": "Usage téléphone", "amount": 90, "location": "", "status": "paid"},
    {"id": "f19", "vehicleId": "v1", "driverId": "d1", "date": "2026-02-09", "reason": "Stationnement", "amount": 105, "location": "", "status": "paid"},
    {"id": "f20", "vehicleId": "v18", "driverId": "d17", "date": "2026-02-06", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f16", "vehicleId": "v6", "driverId": "d5", "date": "2026-02-02", "reason": "Stationnement", "amount": 135, "location": "", "status": "paid"},
    {"id": "f14", "vehicleId": "v2", "driverId": "d2", "date": "2026-01-31", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f15", "vehicleId": "v4", "driverId": "d4", "date": "2026-01-31", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f13", "vehicleId": "", "driverId": "d51", "date": "2026-01-29", "reason": "Excès de vitesse", "amount": 90, "location": "", "status": "paid"},
    {"id": "f11", "vehicleId": "", "driverId": "d49", "date": "2026-01-27", "reason": "Téléphone", "amount": 90, "location": "", "status": "paid"},
    {"id": "f9", "vehicleId": "v20", "driverId": "d19", "date": "2026-01-22", "reason": "Excès de vitesse", "amount": 45, "location": "", "status": "paid"},
    {"id": "f10", "vehicleId": "v20", "driverId": "d19", "date": "2026-01-21", "reason": "Excès de vitesse", "amount": 45, "location": "", "status": "paid"},
    {"id": "f12", "vehicleId": "", "driverId": "d50", "date": "2026-01-19", "reason": "Stationnement", "amount": 47, "location": "", "status": "paid"},
    {"id": "f7", "vehicleId": "v13", "driverId": "d12", "date": "2026-01-16", "reason": "Stationnement", "amount": 135, "location": "", "status": "paid"},
    {"id": "f6", "vehicleId": "v1", "driverId": "d1", "date": "2026-01-15", "reason": "Stationnement", "amount": 157, "location": "", "status": "paid"},
    {"id": "f8", "vehicleId": "v1", "driverId": "d1", "date": "2026-01-15", "reason": "Excès de vitesse", "amount": 90, "location": "", "status": "paid"},
    {"id": "f5", "vehicleId": "v20", "driverId": "d19", "date": "2026-01-09", "reason": "Stationnement", "amount": 35, "location": "", "status": "paid"},
    {"id": "f3", "vehicleId": "v17", "driverId": "d16", "date": "2026-01-07", "reason": "Excès de vitesse", "amount": 90, "location": "", "status": "paid"},
    {"id": "f4", "vehicleId": "v25", "driverId": "d24", "date": "2026-01-07", "reason": "Excès de vitesse", "amount": 45, "location": "", "status": "paid"},
    {"id": "f1", "vehicleId": "v4", "driverId": "d4", "date": "2026-01-03", "reason": "Circulation non autorisé", "amount": 90, "location": "", "status": "paid"},
    {"id": "f2", "vehicleId": "v11", "driverId": "d10", "date": "2025-12-04", "reason": "Excès de vitesse", "amount": 0, "location": "", "status": "paid"},
    {"id": "f26", "vehicleId": "v11", "driverId": "d10", "date": "2025-12-04", "reason": "Excès de vitesse", "amount": 0, "location": "", "status": "paid"},
  ],
  maintenance: [
    {"id": "m1", "vehicleId": "v1", "date": "2025-10-17", "kind": "controle_technique", "cost": 0, "mileage": 43018, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m2", "vehicleId": "v1", "date": "2027-10-17", "kind": "controle_technique", "cost": 0, "mileage": 43018, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m3", "vehicleId": "v2", "date": "2028-01-31", "kind": "controle_technique", "cost": 0, "mileage": 27737, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m4", "vehicleId": "v2", "date": "2025-12-22", "kind": "revision", "cost": 0, "mileage": 27737, "status": "done", "notes": "Dernière révision"},
    {"id": "m5", "vehicleId": "v3", "date": "2025-11-03", "kind": "controle_technique", "cost": 0, "mileage": 76851, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m6", "vehicleId": "v3", "date": "2027-11-03", "kind": "controle_technique", "cost": 0, "mileage": 76851, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m7", "vehicleId": "v3", "date": "2025-10-30", "kind": "revision", "cost": 0, "mileage": 76851, "status": "done", "notes": "Dernière révision"},
    {"id": "m8", "vehicleId": "v4", "date": "2026-01-05", "kind": "controle_technique", "cost": 0, "mileage": 74207, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m9", "vehicleId": "v4", "date": "2028-01-04", "kind": "controle_technique", "cost": 0, "mileage": 74207, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m10", "vehicleId": "v5", "date": "2029-11-25", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m11", "vehicleId": "v6", "date": "2027-09-27", "kind": "controle_technique", "cost": 0, "mileage": 56051, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m12", "vehicleId": "v6", "date": "2025-12-10", "kind": "revision", "cost": 0, "mileage": 56051, "status": "done", "notes": "Dernière révision"},
    {"id": "m13", "vehicleId": "v7", "date": "2025-12-04", "kind": "controle_technique", "cost": 0, "mileage": 186925, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m14", "vehicleId": "v7", "date": "2027-12-03", "kind": "controle_technique", "cost": 0, "mileage": 186925, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m15", "vehicleId": "v7", "date": "2025-04-29", "kind": "revision", "cost": 0, "mileage": 186925, "status": "done", "notes": "Dernière révision"},
    {"id": "m16", "vehicleId": "v8", "date": "2025-05-22", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m17", "vehicleId": "v8", "date": "2027-05-22", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m18", "vehicleId": "v9", "date": "2029-07-25", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m19", "vehicleId": "v10", "date": "2027-06-30", "kind": "controle_technique", "cost": 0, "mileage": 135913, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m20", "vehicleId": "v10", "date": "2026-04-24", "kind": "revision", "cost": 0, "mileage": 135913, "status": "done", "notes": "Dernière révision"},
    {"id": "m21", "vehicleId": "v11", "date": "2027-03-28", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m22", "vehicleId": "v11", "date": "2025-12-02", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m23", "vehicleId": "v12", "date": "2027-03-28", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m24", "vehicleId": "v12", "date": "2025-07-31", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m25", "vehicleId": "v13", "date": "2027-05-15", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m26", "vehicleId": "v13", "date": "2025-12-22", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m27", "vehicleId": "v14", "date": "2025-04-01", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m28", "vehicleId": "v14", "date": "2027-03-31", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m29", "vehicleId": "v14", "date": "2026-03-27", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m30", "vehicleId": "v15", "date": "2027-06-28", "kind": "controle_technique", "cost": 0, "mileage": 47000, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m31", "vehicleId": "v16", "date": "2030-02-18", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m32", "vehicleId": "v17", "date": "2030-03-16", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m33", "vehicleId": "v18", "date": "2029-10-15", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m34", "vehicleId": "v19", "date": "2029-09-26", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m35", "vehicleId": "v20", "date": "2029-12-24", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m36", "vehicleId": "v21", "date": "2025-02-26", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m37", "vehicleId": "v21", "date": "2027-02-25", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m38", "vehicleId": "v21", "date": "2026-01-27", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m39", "vehicleId": "v22", "date": "2025-12-15", "kind": "controle_technique", "cost": 0, "mileage": 96973, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m40", "vehicleId": "v22", "date": "2027-12-14", "kind": "controle_technique", "cost": 0, "mileage": 96973, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m41", "vehicleId": "v22", "date": "2026-05-04", "kind": "revision", "cost": 0, "mileage": 96973, "status": "done", "notes": "Dernière révision"},
    {"id": "m42", "vehicleId": "v23", "date": "2026-07-07", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m43", "vehicleId": "v23", "date": "2025-12-23", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m44", "vehicleId": "v24", "date": "2025-01-21", "kind": "controle_technique", "cost": 0, "mileage": 98751, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m45", "vehicleId": "v24", "date": "2027-01-20", "kind": "controle_technique", "cost": 0, "mileage": 98751, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m46", "vehicleId": "v24", "date": "2026-04-30", "kind": "revision", "cost": 0, "mileage": 98751, "status": "done", "notes": "Dernière révision"},
    {"id": "m47", "vehicleId": "v25", "date": "2029-12-29", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m48", "vehicleId": "v26", "date": "2027-07-06", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m49", "vehicleId": "v26", "date": "2026-01-05", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m50", "vehicleId": "v28", "date": "2025-11-26", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m51", "vehicleId": "v29", "date": "2025-07-02", "kind": "controle_technique", "cost": 0, "mileage": 105399, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m52", "vehicleId": "v29", "date": "2025-09-01", "kind": "controle_technique", "cost": 0, "mileage": 105399, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m53", "vehicleId": "v29", "date": "2025-08-20", "kind": "revision", "cost": 0, "mileage": 105399, "status": "done", "notes": "Dernière révision"},
    {"id": "m54", "vehicleId": "v30", "date": "2025-12-09", "kind": "controle_technique", "cost": 0, "mileage": 98608, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m55", "vehicleId": "v30", "date": "2027-12-01", "kind": "controle_technique", "cost": 0, "mileage": 98608, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m56", "vehicleId": "v30", "date": "2025-12-31", "kind": "revision", "cost": 0, "mileage": 98608, "status": "done", "notes": "Dernière révision"},
    {"id": "m57", "vehicleId": "v31", "date": "2025-06-20", "kind": "controle_technique", "cost": 0, "mileage": 82057, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m58", "vehicleId": "v31", "date": "2027-06-19", "kind": "controle_technique", "cost": 0, "mileage": 82057, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m59", "vehicleId": "v31", "date": "2026-03-27", "kind": "revision", "cost": 0, "mileage": 82057, "status": "done", "notes": "Dernière révision"},
    {"id": "m60", "vehicleId": "v32", "date": "2026-02-05", "kind": "controle_technique", "cost": 0, "mileage": 145104, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m61", "vehicleId": "v32", "date": "2028-02-01", "kind": "controle_technique", "cost": 0, "mileage": 145104, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m62", "vehicleId": "v32", "date": "2025-07-09", "kind": "revision", "cost": 0, "mileage": 145104, "status": "done", "notes": "Dernière révision"},
    {"id": "m63", "vehicleId": "v33", "date": "2025-05-03", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m64", "vehicleId": "v33", "date": "2027-05-02", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m65", "vehicleId": "v33", "date": "2026-01-16", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m66", "vehicleId": "v34", "date": "2029-12-29", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m67", "vehicleId": "v35", "date": "2026-10-24", "kind": "controle_technique", "cost": 0, "mileage": 68242, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m68", "vehicleId": "v35", "date": "2026-03-05", "kind": "revision", "cost": 0, "mileage": 68242, "status": "done", "notes": "Dernière révision"},
    {"id": "m69", "vehicleId": "v36", "date": "2026-10-24", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m70", "vehicleId": "v36", "date": "2026-01-23", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m71", "vehicleId": "v37", "date": "2029-10-01", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m72", "vehicleId": "v38", "date": "2030-03-23", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m73", "vehicleId": "v39", "date": "2025-03-25", "kind": "controle_technique", "cost": 0, "mileage": 131715, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m74", "vehicleId": "v39", "date": "2027-03-24", "kind": "controle_technique", "cost": 0, "mileage": 131715, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m75", "vehicleId": "v39", "date": "2025-12-12", "kind": "revision", "cost": 0, "mileage": 131715, "status": "done", "notes": "Dernière révision"},
    {"id": "m76", "vehicleId": "v40", "date": "2026-05-19", "kind": "controle_technique", "cost": 0, "mileage": 132131, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m77", "vehicleId": "v40", "date": "2027-12-10", "kind": "controle_technique", "cost": 0, "mileage": 132131, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m78", "vehicleId": "v40", "date": "2025-12-24", "kind": "revision", "cost": 0, "mileage": 132131, "status": "done", "notes": "Dernière révision"},
    {"id": "m79", "vehicleId": "v41", "date": "2026-10-04", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m80", "vehicleId": "v43", "date": "2025-01-20", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m81", "vehicleId": "v43", "date": "2027-01-19", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m82", "vehicleId": "v43", "date": "2026-04-03", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m83", "vehicleId": "v44", "date": "2025-04-17", "kind": "controle_technique", "cost": 0, "mileage": 77000, "status": "done", "notes": "Dernier contrôle technique"},
    {"id": "m84", "vehicleId": "v44", "date": "2027-04-16", "kind": "controle_technique", "cost": 0, "mileage": 77000, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m85", "vehicleId": "v44", "date": "2025-12-03", "kind": "revision", "cost": 0, "mileage": 77000, "status": "done", "notes": "Dernière révision"},
    {"id": "m86", "vehicleId": "v45", "date": "2026-09-30", "kind": "controle_technique", "cost": 0, "mileage": 61828, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m87", "vehicleId": "v45", "date": "2026-05-07", "kind": "revision", "cost": 0, "mileage": 61828, "status": "done", "notes": "Dernière révision"},
    {"id": "m88", "vehicleId": "v46", "date": "2026-10-24", "kind": "controle_technique", "cost": 0, "mileage": 0, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m89", "vehicleId": "v46", "date": "2025-12-12", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
    {"id": "m90", "vehicleId": "v47", "date": "2026-09-30", "kind": "controle_technique", "cost": 0, "mileage": 55673, "status": "scheduled", "notes": "Contrôle technique à effectuer"},
    {"id": "m91", "vehicleId": "v47", "date": "2025-09-01", "kind": "revision", "cost": 0, "mileage": 55673, "status": "done", "notes": "Dernière révision"},
    {"id": "m92", "vehicleId": "v52", "date": "2025-10-14", "kind": "revision", "cost": 0, "mileage": 0, "status": "done", "notes": "Dernière révision"},
  ],
  trips: [],
};
